### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by sxjzwq** [jiasenlu/visDial.pytorch#1]
Is this the final version? It seems that there are many errors in the training script. I fix some typos in train_D and train_G. But there are still many in the train_all.

Loading txt from data/visdial_data.h5
Vocab Size: 8964
init Discriminator model...
Loading Discriminator model...
init Generative model...
Loading Generative model...
[u'yes ', u'boy i think ', u'yes or it there is setting in distance ', u'blond ', u'yes ', u'holding and walking ', u'i think so 5 ', u'white ', u'it looks blue ', u'same white ', u'blue mets , grey and red ', u'no people ', u'yes , it looks like a semi truck ', u'yes ', u'1 ', u'yes , really ', u'outdoors ', u'i see 2 ', u'there are no people that i can see ', u'correct passengers cow running ', u'yes ', u'yes it is ', u'red and white ', u'can not tell ', u'a boy ', u'3 ', u'no ! just the 2 halves ', u'many very things really equipment , boxes maybe ', u'male ', u'probably 8 ', u'no ', u'white ', u'no people ', u"about mid 20 's ", u'yes ', u'yes ', u'no people ', u'no ', u'black and red ', u'pepperoni on some sort ', u'yes ', u'yes ', u'on a road ', u'no ', u'yes ', u'no ', u'khaki shorts ', u'white ', u'i think it looks like it has rained ', u'looks like a toddler ', u'no ', u"does n't any items ", u'yes ', u'it is hard to see really many ', u'no , concrete ', u'no ', u'yes ', u'yes ', u'yes ', u'medium sized digital ', u"no , it 's straight linoleum ", u'yes ', u'no only 1 is ', u'meat maybe carrots ', u'it seems to be alone ', u'yes , about 6 people ', u'white ', u'white ', u'smaller plane ', u'a stove ', u'stone ', u'black , red , blue , white and ', u'i can only see his lower half but ', u'yes ', u'11 people ', u'no , there is just 1 tree that ', u'about thirty ', u'yes ', u'do not know i only see back from ', u'orange and orange ', u'yes ', u"it 's brown ", u'a man ', u"ca n't tell ", u'no ', u'2 players and ump ', u'yes ', u"i do n't think so i only see ", u'yes it is ', u'yes ', u'yes it is ', u'small ', u'small gulls ', u'yes ', u'yes ', u'3 ', u'no diameter ', u'tan ', u'yes ', u'the plates is white ']
Traceback (most recent call last):
  File "./train/train_all.py", line 638, in <module>
    train_loss_lm, train_loss_d, train_loss_g, loss_store = train(epoch)
  File "./train/train_all.py", line 390, in train
    ans_fake_emb = netW_d(fake_onehot, format='onehot') # not detach here.
  File "/home/tommy/anaconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tommy/visDial.pytorch/misc/model.py", line 24, in forward
    out = F.dropout(self.Linear(input), self.d, training=self.training)
  File "/home/tommy/anaconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tommy/visDial.pytorch/misc/share_Linear.py", line 43, in forward
    return self._backend.Linear.apply(input, self.weight)
  File "/home/tommy/anaconda/lib/python2.7/site-packages/torch/nn/backends/backend.py", line 10, in __getattr__
    raise NotImplementedError
NotImplementedError

Can you help to solve the above errors?

**Comment by sxjzwq** [comment]
The issue happens when call

ans_fake_emb = netW_d(fake_onehot, format='onehot') # not detach here.
out = F.dropout(self.Linear(input), self.d, training=self.training)
return self._backend.Linear.apply(input, self.weight)

Please note I fix Line 157
netG = _netG(opt.model, vocab_size, opt.ninp, opt.nhid, opt.nlayers, opt.dropout, vocab_size)
->
netG = _netG(opt.model, vocab_size, opt.ninp, opt.nhid, opt.nlayers, opt.dropout)
because there should be 6 inputs, you have one more.

and Line 295
one_hot, idx = sampler(logprob, noise_input[di], opt.gumble_weight)
->
one_hot, idx, lg= sampler(logprob, noise_input[di], opt.gumble_weight)
because there should be three outputs.

Nothing else, then I met above errors.

**Comment by jiasenlu** [comment]
Hi
The problem is due to the new pytorch version. I've adjusted the code. You can try it again. 

Jiasen
